// Generated by Wrangler by running `wrangler types`

interface Env {
	USERS: KVNamespace;
	PROJECTS: KVNamespace;
	API_KEYS: KVNamespace;
	ENVIRONMENT: "development" | "production";
	CORS_ORIGIN: "*";
}
